# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np


#### 2. Print the numpy version and the configuration (★☆☆)

#### 3. Create a null vector of size 10 (★☆☆)

#### 4. How to find the memory size of any array (★☆☆)

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

#### 8. Reverse a vector (first element becomes last) (★☆☆)

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

#### 11. Create a 3x3 identity matrix (★☆☆)

#### 12. Create a 3x3x3 array with random values (★☆☆)

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [2]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [6]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
Z


array([[0.5378308 , 0.29256333, 0.37268833, 0.36491706, 0.59538372],
       [0.39527047, 0.6007458 , 0.32636356, 0.08611809, 0.61329293],
       [0.37238248, 0.37145611, 0.76174385, 0.69636678, 0.32054856],
       [0.13259   , 0.352298  , 0.7354849 , 0.53320079, 0.04752433],
       [0.31642135, 0.42764956, 0.11070139, 0.10088048, 0.60982234]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [8]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [12]:
Z = np.matmul(np.ones((5,3)),np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [14]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [16]:
from numpy import *
print(sum(range(5),-1))

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [19]:
Z <- Z

array([False, False, False, False,  True,  True,  True,  True, False,
       False, False])

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [22]:

np.array([np.nan]).astype(int).astype(float)


/tmp/ipykernel_19978/1499642010.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

SyntaxError: invalid syntax (3431500736.py, line 1)

#### 30. How to find common values between two arrays? (★☆☆) вивід тих які не перетинаються

In [26]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))


[1 4 5 9]


array([5, 3, 9, 5, 4, 2, 2, 2, 1, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [31]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0


array([nan, inf, inf])

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [3]:
import numpy as np
np.sqrt(-1) == np.emath.sqrt(-1)

/tmp/ipykernel_6349/3084084354.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [11]:
tomorrow = np.datetime64('today') + np.timedelta64(1)
today = np.datetime64('today')
yesterday = np.datetime64('today') - np.timedelta64(1)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [13]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [14]:
A = np.ones(3) * 1
B = np.ones(3) * 2

np.add(A,B,out=B)
np.negative(A, out=A)
np.divide(A, 2, out=A)
np.multiply(A, B, out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)
ий метод обрати?
astype(int) — найкращий, якщо вам потрібно змінити тип даних масиву (наприклад, з 7.0 на 7), щоб зекономити пам'ять.

trunc() або floor() — кращі, якщо ви хочете залишити результат у форматі float (наприклад, 7.0), що часто потрібно для подальших математичних обчислень.

In [20]:
Z = np.random.uniform(0,10,10)
np.trunc(Z)
np.floor(Z)
Z.astype(int)
Z - Z % 1

array([5., 5., 9., 6., 6., 9., 1., 4., 5., 7.])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [22]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [23]:
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [29]:
def gener():
    for x in range(10):
        yield x
Z = np.fromiter(gener(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [31]:
Z = np.linspace(0,1,11,endpoint=False)[1:]

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [32]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.16630988 0.21371625 0.33466958 0.35768374 0.54643421 0.55326197
 0.59350582 0.60778415 0.81478464 0.94219239]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [36]:
Z = np.arange(10)
Z
np.add.reduce(Z)

np.int64(45)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [2]:
import numpy as np
X = np.array(np.arange(10))
Y = np.arange(10)


A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(np.allclose(A,B))
# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [18]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] =1


ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [35]:
Z = np.random.random((10,2))
X, Y = Z[:,0],Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[1.37404767 0.18652203 0.41193073 0.97475006 0.54510796 0.87848482
 0.15514333 1.21023217 0.85529805 0.5655932 ]
[0.75962299 1.01713799 0.74547227 0.26991139 0.68236358 0.01477883
 0.11796566 0.66598472 1.20668102 0.85841304]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [43]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
Z

array([0.14827023, 0.34231982, 0.49194087, 0.3822071 , 0.49655406,
       0.93522249, 0.95980189, 0.96763545, 0.53429615, 0.        ])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [3]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

In [4]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [10]:
np.set_printoptions(precision = 3)
Z = np.random.random(10)
print(Z)

[0.39  0.214 0.544 ... 0.548 0.99  0.498]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [26]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])
print(np.abs(v).argmin())

1
0


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [31]:
Z = np.zeros(1, [ ('position', [ ('x', int, 1),
                                  ('y', int, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[(([0], [0]), ([0.], [0.], [0.]))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [38]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.    0.606 0.412 ... 0.747 0.298 0.725]
 [0.606 0.    0.52  ... 0.142 0.336 0.163]
 [0.412 0.52  0.    ... 0.623 0.263 0.545]
 ...
 [0.747 0.142 0.623 ... 0.    0.47  0.109]
 [0.298 0.336 0.263 ... 0.47  0.    0.432]
 [0.725 0.163 0.545 ... 0.109 0.432 0.   ]]
[[0.    0.532 0.366 ... 0.491 0.889 0.354]
 [0.532 0.    0.448 ... 0.778 0.688 0.439]
 [0.366 0.448 0.    ... 0.332 0.526 0.014]
 ...
 [0.491 0.778 0.332 ... 0.    0.671 0.34 ]
 [0.889 0.688 0.526 ... 0.671 0.    0.536]
 [0.354 0.439 0.014 ... 0.34  0.536 0.   ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

In [48]:
Z = (np.random.rand(10)*100).astype(np.float32)
print(Z)
Y = Z.view(np.int32)
print(Y)
Y[:] = Z
print(Y)

[ 0.715 14.201 84.008 ... 99.956 88.713 42.813]
[1060568627 1097020990 1118307325 ... 1120397713 1118924064 1110130723]
[ 0 14 84 ... 99 88 42]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)